import type { Metadata } from "next";
import { Inter } from "next/font/google"
import AuthProvider from "../../context/AuthProvider"
import "../../globals.css"
import { locales } from "../../../i18n"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string
  }
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <AuthProvider>
        <body className={inter.className}>{children}</body>
      </AuthProvider>
    </html>
  )
}
